### ISSUE TITLE
Failed to connect to PostgresSQL after creating the binding

### ISSUE THREAD

**Issue by arunneoz** [fusor/catasb#44]
Hi ,

I have successfully provisioned the ec2 instance and everything is working perfectly except when i try to create the binding, it is creating the secrets with all the parameters for postgres , except the application is not able to retrieve it. 

Am i missing any steps ?

![image](https://cloud.githubusercontent.com/assets/9501433/25832702/cd349628-3431-11e7-8b84-b1cefc1445b5.png)

**Comment by jwmatthews** [comment]
I wonder if the issue is that several bindings exist.  I would expect to see only 1 binding for the service.  

Please:
1) Retry the workflow with a clean run, i.e. run "reset_environment.sh", then use 'aws-demo' project.
2) Provision one RDS, wait till you know the RDS is up, look at the logs from the APB as the RDS is provisioned (logs are under the ansible-service-broker project for the aa-* pod)
3) Provision the Python WebApp
4) Wait till the WebApp is up and you can see the map display
5) Click the Kebab Menu on the WebApp
6) Select 'Create Binding'
7) Select the rds-postgres-apb
8) Click Bind
9) Watch the Python webapp create a new deployment, wait for the deployment to complete, give it a few more seconds to finish
10) Reload the python webapp.

Please let us know how this works for you.

**Comment by arunneoz** [comment]
Thanks the reset environment did the trick

**Comment by jwmatthews** [comment]
@arunneoz great to hear it worked for you.
